### ISSUE TITLE
How can I obtain the cartoon dataset?

### ISSUE THREAD

**Issue by Stuyxr** [FilipAndersson245/cartoon-gan#1]
What a wonderful job! And I am wondering how to obtain the cartoon dataset. Thank you.

**Comment by zimonitrome** [comment]
Thanks!
Unfortunately we are not able to share the cartoon dataset since the works are copyrighted. As mentioned in the paper, we use frames from movies by Studio Ghibli. You would have to extract images from your own copies of those movies.

**Comment by Aspie96** [comment]
I think the question still stands: may you provide the means for obtaining the dataset?
I mean the scripts you used to download it and prepare it.

By the way, thank you for sharing your work!

**Comment by zimonitrome** [comment]
A lot of the processing was done "manually" (read: trial and error) through cli commands and I believe any notes we had on that are now gone.

We are looking into providing a general script that can take any video file and produce desired images (resized and all) but I believe any release would be at least 2 months away.

Thanks for taking an interest in our work and hopefully we can improve upon it soon!

**Comment by Aspie96** [comment]
This is understandable.
Thank you a lot!
