### ISSUE TITLE
load video

### ISSUE THREAD

**Issue by KirillHiddleston** [FilipAndersson245/cartoon-gan#10]
Hi, nice work

```
predict.py -i ./input -o ./output_folder
Processing files:   0%|                                                                                                                                   | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "predict.py", line 113, in <module>
    predict_file(file_path, output_file_path)
  File "predict.py", line 55, in predict_file
    if mimetypes.guess_type(input_path)[0].startswith("image"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
I trying predicting videos (.mpeg format file), but AttributeError: 'NoneType' object has no attribute 'startswith'
can u help please ?
and what do you mean "predicting videos FFmpeg'"

**Comment by zimonitrome** [comment]
FFMPEG is a tool that is needed if you want to convert videos. I would say try to download and install FFMPEG (add to your path) and use FFMPEG to convert your mpeg videos to mp4 videos, that format worked the best for us.
