### ISSUE TITLE
Weights license

### ISSUE THREAD

**Issue by Aspie96** [FilipAndersson245/cartoon-gan#11]
Hi. Thank you for sharing this work!

Is everything in the folder:
https://drive.google.com/drive/folders/1d_GsZncTGmMdYht0oUWG9pqvV4UqF_kM

licensed under the same MIT license as this repository?

I do know you don't own the dataset. I am referring to rights on the model other than those that exist because of the dataset (if any).

**Comment by zimonitrome** [comment]
Yes the weights can be used under the MIT license :)

**Comment by Aspie96** [comment]
Thanks!

If you'd like, consider adding a license file to the directory (for those that don't see this issue).
