### ISSUE TITLE
Memory and pading error

### ISSUE THREAD

**Issue by roxy0230** [FilipAndersson245/cartoon-gan#13]
Hello. Thanks for the other answer. I did that change and now I have a problem with the memory. If you can further help me?

RuntimeError: CUDA out of memory. Tried to allocate 134.00 MiB (GPU 0; 6.00 GiB total capacity; 5.15 GiB already allocated; 0 bytes free; 5.34 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I saw that someone else had the problem and you suggested lowering the batch size. I also did that and got (I changed it to 16):
RuntimeError: 3D or 4D (batch mode) tensor expected for input, but got: [ torch.cuda.FloatTensor{16,3,256,0} ]

I lowered the image size but it still goes out of memory.

And when I do both it gives:
RuntimeError: Padding size should be less than the corresponding input dimension, but got: padding (1, 1) at dimension 3 of input [16, 64, 128, 1]

**Comment by FilipAndersson245** [comment]
Both lowering the batch size, and the image size will reduce the quality of the training, as one part of the network is pre-trained on this resolution and will not perform well if lowered in much future, Batch size will also affect the stability if lower too much but probably be okay to lower its future.
I would recommend to set [this](https://github.com/FilipAndersson245/cartoon-gan/blob/04d7f331d9366eb47b3685136df0af24f466aa3e/train.py#L24) to 1 and then increment until you cannot run the code to find the maximum batch size, If it has to be dividable by 2, so test 1,2,4 etc.

**Comment by roxy0230** [comment]
> Both lowering the batch size, and the image size will reduce the quality of the training, as one part of the network is pre-trained on this resolution and will not perform well if lowered in much future, Batch size will also affect the stability if lower too much but probably be okay to lower its future. I would recommend to set [this](https://github.com/FilipAndersson245/cartoon-gan/blob/04d7f331d9366eb47b3685136df0af24f466aa3e/train.py#L24) to 1 and then increment until you cannot run the code to find the maximum batch size, If it has to be dividable by 2, so test 1,2,4 etc.

If I do this change I shows:

Starting Training Loop...
training epoch  0
Traceback (most recent call last):
  File "train.py", line 158, in <module>
    train()
  File "train.py", line 93, in train
    edge_pred      = netD(edge_data)         #.view(-1)
  File "E:\Anaconda\envs\CartoonGAN\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Proiecte_Dizertatie\cartoon-gan\models\discriminator.py", line 35, in forward
    x = self.conv(x)
  File "E:\Anaconda\envs\CartoonGAN\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Anaconda\envs\CartoonGAN\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "E:\Anaconda\envs\CartoonGAN\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Anaconda\envs\CartoonGAN\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "E:\Anaconda\envs\CartoonGAN\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Anaconda\envs\CartoonGAN\lib\site-packages\torch\nn\modules\padding.py", line 174, in forward
    return F.pad(input, self.padding, 'reflect')
  File "E:\Anaconda\envs\CartoonGAN\lib\site-packages\torch\nn\functional.py", line 4189, in _pad
    return torch._C._nn.reflection_pad2d(input, pad)
RuntimeError: 3D or 4D (batch mode) tensor expected for input, but got: [ torch.cuda.FloatTensor{4,3,256,0} ]

**Comment by roxy0230** [comment]
> Both lowering the batch size, and the image size will reduce the quality of the training, as one part of the network is pre-trained on this resolution and will not perform well if lowered in much future, Batch size will also affect the stability if lower too much but probably be okay to lower its future. I would recommend to set [this](https://github.com/FilipAndersson245/cartoon-gan/blob/04d7f331d9366eb47b3685136df0af24f466aa3e/train.py#L24) to 1 and then increment until you cannot run the code to find the maximum batch size, If it has to be dividable by 2, so test 1,2,4 etc.

I also left my batch size on 256, and my data set has images of 256x256. I don't know if it is it but it looks like a problem with the padding or the tensor dimensions. Is there a way I can fix it? Thanks

**Comment by FilipAndersson245** [comment]
I am a bit unsure what this may be, @zimonitrome you have any ide?

**Comment by zimonitrome** [comment]
Hi @roxy0230, I could try to look into this further in a few days. In the meantime, could you maybe try to add `print(x.shape)` right before `x = self.conv(x)` in `E:\Proiecte_Dizertatie\cartoon-gan\models\discriminator.py`?

**Comment by roxy0230** [comment]
> Hi @roxy0230, I could try to look into this further in a few days. In the meantime, could you maybe try to add `print(x.shape)` right before `x = self.conv(x)` in `E:\Proiecte_Dizertatie\cartoon-gan\models\discriminator.py`?

Hello. I made a change meanwhile here  https://github.com/FilipAndersson245/cartoon-gan/blob/04d7f331d9366eb47b3685136df0af24f466aa3e/train.py#L84 And it started running. I changed it to 
```
            cartoon_data   = cartoon_edge_data[:, :, :, :image_size].to(device)
            edge_data      = cartoon_edge_data[:, :, :, :image_size:].to(device)
```

but I don't know if that is ok because the images did not generate properly and I don't know if it is from this or because the batch_size was on 4. I will try some more changes and also do the print that @zimonitrome said. Thanks and I will wait for your reply on the issue

**Comment by roxy0230** [comment]
> Hi @roxy0230, I could try to look into this further in a few days. In the meantime, could you maybe try to add `print(x.shape)` right before `x = self.conv(x)` in `E:\Proiecte_Dizertatie\cartoon-gan\models\discriminator.py`?

I did the print and it shows:
Starting Training Loop...
training epoch  0
torch.Size([4, 3, 256, 256])
torch.Size([4, 3, 256, 0])

**Comment by roxy0230** [comment]
> Hi @roxy0230, I could try to look into this further in a few days. In the meantime, could you maybe try to add `print(x.shape)` right before `x = self.conv(x)` in `E:\Proiecte_Dizertatie\cartoon-gan\models\discriminator.py`?

I had an impression that it might be a problem with the shape this is why I modified it as mentioned above but the change doesn't feel right because the images don't change from one epoch to another like the model is not training, or it doesn't consider the pretrained model I'am using at all. The losses also increased after like 4-5 epochs for some reason. So I feel like there should be another change or I am doing something wrong.

**Comment by zimonitrome** [comment]
Hello @roxy0230, sorry for taking some time to respond.

What does your cartoon images look like?

Images should be `w = 2ximage_size` and `h = image_size` where the first `image_size x image_size` is the cartoon image, ant to the left of it is the same image but with edges blurred. And thus 

```
            cartoon_data   = cartoon_edge_data[:, :, :, :image_size].to(device) # x axis pixels 0 to image_size 
            edge_data      = cartoon_edge_data[:, :, :, image_size:].to(device) # x axis pixels image_size to the end
```

splits the image into these two parts when training.

Your change seemingly selects x axis pixels 0 to image_size and then x axis pixels 0 to image_size again. So cartoon_data and edge_data is the same. This means that the model trains to produce a certain image but gets penalized for producing that image. Not good.

Maybe this is the problem I see from the print aswell? Maybe your images are `w = image_size` and `h = image_size` instead of `w = 2ximage_size` and `h = image_size`?

**Comment by roxy0230** [comment]
> Hello @roxy0230, sorry for taking some time to respond.
> 
> What does your cartoon images look like?
> 
> Images should be `w = 2ximage_size` and `h = image_size` where the first `image_size x image_size` is the cartoon image, ant to the left of it is the same image but with edges blurred. And thus
> 
> ```
>             cartoon_data   = cartoon_edge_data[:, :, :, :image_size].to(device) # x axis pixels 0 to image_size 
>             edge_data      = cartoon_edge_data[:, :, :, image_size:].to(device) # x axis pixels image_size to the end
> ```
> 
> splits the image into these two parts when training.
> 
> Your change seemingly selects x axis pixels 0 to image_size and then x axis pixels 0 to image_size again. So cartoon_data and edge_data is the same. This means that the model trains to produce a certain image but gets penalized for producing that image. Not good.
> 
> Maybe this is the problem I see from the print aswell? Maybe your images are `w = image_size` and `h = image_size` instead of `w = 2ximage_size` and `h = image_size`?

Hello @zimonitrome , thanks for your reply. I changed the cartoon images to have w = 2 x image size and h = image size with the code you have provided but the generated images still don't seem to evolve much or at all. This might be due to my smaller dataset right? Or is it another problem? The outputs are very similar to before and even if I use one of the trained models, it just falls back to the poorly generated images (they look like their input image).

Also, if I want to continue training from a checkpoint I saw that I should write:
                    `netG.load_state_dict(torch.load("./checkpoints/pretrained_netG_checkpoint1.pth"))`
 instead of 
                    `netG.load_state_dict(torch.load("./checkpoints/pretrained_netG_checkpoint1.pth").state_dict())`

because it outputs an error. 

Is it still correct to do it this way or does it lose some data?
Also, should I add the discriminator to the training too?

**Comment by zimonitrome** [comment]
@roxy0230

It might be due to a smaller dataset but more likely due to not training long enough. How many images do you have and how many epoch have you trained for? We trained with around 60'000 images for 10 epochs which results in the discriminator seeing a total of 600'000 images.

This GAN in particular was made to be trained slowly, which means that images will look similar from epoch to epoch. IIRC we started seeing a meaningful difference from epoch 0 to epoch 6 or 8 somewhere.

> Also, if I want to continue training from a checkpoint I saw that I should write:
netG.load_state_dict(torch.load("./checkpoints/pretrained_netG_checkpoint1.pth"))
instead of
netG.load_state_dict(torch.load("./checkpoints/pretrained_netG_checkpoint1.pth").state_dict())
> because it outputs an error.
> Is it still correct to do it this way or does it lose some data?

No, that should be fine. Saving a model or it's state dict is a common mistake I make so it might have been a blunder on my part. You always want the state dict so it should be fine.

> Also, should I add the discriminator to the training too?

How are you training it right now? You should always train both the Generator and the Discriminator. If you are asking if you should save both of them to continue training later, then the answer is yes.

**Comment by roxy0230** [comment]
> @roxy0230
> 
> It might be due to a smaller dataset but more likely due to not training long enough. How many images do you have and how many epoch have you trained for? We trained with around 60'000 images for 10 epochs which results in the discriminator seeing a total of 600'000 images.
> 
> This GAN in particular was made to be trained slowly, which means that images will look similar from epoch to epoch. IIRC we started seeing a meaningful difference from epoch 0 to epoch 6 or 8 somewhere.
> 
> > Also, if I want to continue training from a checkpoint I saw that I should write:
> > netG.load_state_dict(torch.load("./checkpoints/pretrained_netG_checkpoint1.pth"))
> > instead of
> > netG.load_state_dict(torch.load("./checkpoints/pretrained_netG_checkpoint1.pth").state_dict())
> > because it outputs an error.
> > Is it still correct to do it this way or does it lose some data?
> 
> No, that should be fine. Saving a model or it's state dict is a common mistake I make so it might have been a blunder on my part. You always want the state dict so it should be fine.
> 
> > Also, should I add the discriminator to the training too?
> 
> How are you training it right now? You should always train both the Generator and the Discriminator. If you are asking if you should save both of them to continue training later, then the answer is yes.

Thank you for all your help.  Also thank you @FilipAndersson245  for your help too.
I left it train for 1000 epochs and the dataset consists of around 1800 images. I think that will be enough untill I get to the end.  O got to epoch 400 an it starts to look better.

**Comment by roxy0230** [comment]
> @roxy0230
> 
> It might be due to a smaller dataset but more likely due to not training long enough. How many images do you have and how many epoch have you trained for? We trained with around 60'000 images for 10 epochs which results in the discriminator seeing a total of 600'000 images.
> 
> This GAN in particular was made to be trained slowly, which means that images will look similar from epoch to epoch. IIRC we started seeing a meaningful difference from epoch 0 to epoch 6 or 8 somewhere.
> 
> > Also, if I want to continue training from a checkpoint I saw that I should write:
> > netG.load_state_dict(torch.load("./checkpoints/pretrained_netG_checkpoint1.pth"))
> > instead of
> > netG.load_state_dict(torch.load("./checkpoints/pretrained_netG_checkpoint1.pth").state_dict())
> > because it outputs an error.
> > Is it still correct to do it this way or does it lose some data?
> 
> No, that should be fine. Saving a model or it's state dict is a common mistake I make so it might have been a blunder on my part. You always want the state dict so it should be fine.
> 
> > Also, should I add the discriminator to the training too?
> 
> How are you training it right now? You should always train both the Generator and the Discriminator. If you are asking if you should save both of them to continue training later, then the answer is yes.

A last question (I hope)  would be an advice on how low should the loss for G and D be.  I know it depends on how the output looks but what loss did you got at the end?

**Comment by zimonitrome** [comment]
400 * 1800 = 720000 so you should probably have seen better results before then but again, your dataset is a fair bit smaller so I am not sure.

Unfortunately I don't think we have the loss saved. GAN loss curves can have all sort of shapes and still generate a good output. In my experience, GANs seldom converge well and should instead be stopped when you feel happy with the output.

**Comment by roxy0230** [comment]
> 400 * 1800 = 720000 so you should probably have seen better results before then but again, your dataset is a fair bit smaller so I am not sure.
> 
> Unfortunately I don't think we have the loss saved. GAN loss curves can have all sort of shapes and still generate a good output. In my experience, GANs seldom converge well and should instead be stopped when you feel happy with the output.

Thank you.  I will let ot train further. Probably until 1000 epochs to conclude it. Thanks again.

**Comment by FilipAndersson245** [comment]
> A last question (I hope) would be an advice on how low should the loss for G and D be. I know it depends on how the output looks but what loss did you got at the end?
The loss landscape is very difficult in GANS so the loss may be somewhat misleading, where the Generator produces noise that does manage to trick the Discriminator, and vice versa but fail to produce good generated results.

As you seem to manage it now I will close this issue 😄.
