### ISSUE TITLE
Hello, the link of checkpoint has been removed, could you share a new link ?

### ISSUE THREAD

**Issue by Overcautious** [FilipAndersson245/cartoon-gan#8]

**Comment by zimonitrome** [comment]
The weights were moved to Google Drive. Does this link not work for you?

https://drive.google.com/drive/folders/1d_GsZncTGmMdYht0oUWG9pqvV4UqF_kM?usp=sharing

**Comment by Overcautious** [comment]
> The weights were moved to Google Drive. Does this link not work for you?
> 
> https://drive.google.com/drive/folders/1d_GsZncTGmMdYht0oUWG9pqvV4UqF_kM?usp=sharing

yes，thank you
